name: .NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Print .NET version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore ./BabylonGameEngine.sln

    - name: Build
      run: dotnet build --no-restore ./BabylonGameEngine.sln

    - name: Test
      run: dotnet test --no-restore ./BabylonGameEngine.sln
