jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Restore dependencies
        run: dotnet restore ./BabylonGameEngine.sln

      - name: Build
        run: dotnet build ./BabylonGameEngine.sln --configuration Release

      - name: Test
        run: dotnet test ./BabylonGameEngine.sln --no-build --verbosity normal
