name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install
        continue-on-error: true
        env:
          CI: true

      - name: Print .NET version
        run: dotnet --version

      - name: Build
        run: dotnet build --no-restore --verbosity detailed
        continue-on-error: true

      - name: Test
        run: dotnet test --no-build --verbosity detailed
        continue-on-error: true
