name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./BabylonGameEngine.sln

    - name: Build
      run: dotnet build ./BabylonGameEngine.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./BabylonGameEngine.sln --no-restore --verbosity normal
